### ISSUE TITLE
getFromTypeIndex docs

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/solid-typeindex-support#1]
https://pondersource.github.io/solid-typeindex-support/solid-typeindex-support.typeindexhelper.getfromtypeindex.html

* great work!
* "true" is not a type, I think you mean "boolean"
* rdfClass is a "string", but does it need to be a full URL? Can prefixes be used?

**Comment by itsrezasoltani** [comment]
fixed the boolean flag

**Comment by itsrezasoltani** [comment]
for the `rdfClass`:
yes, it always has to be a valid URL, so I will add it to jsDoc, then it will be resulted in the docs
