### ISSUE TITLE
registerInTypeIndex docs

### ISSUE THREAD

**Issue by michielbdejong** [pondersource/solid-typeindex-support#2]
https://pondersource.github.io/solid-typeindex-support/solid-typeindex-support.typeindexhelper.registerintypeindex.html

* Great work!
* What is a 'type registration title'?
* Where can I get the indexUrl from?
* What is a SolidDataSet?

**Comment by itsrezasoltani** [comment]
`typeRegistrationTitle` is the main thing that will make the typeRegistration unique from others.
```turtle
@prefix : <#>.
@prefix solid: <http://www.w3.org/ns/solid/terms#>.
@prefix bookm: <http://www.w3.org/2002/01/bookmark#>.
@prefix bookmark: </bookmarks/>.

<> a solid:TypeIndex, solid:UnlistedDocument.


:my-bookmarks-registery
    a solid:TypeRegistration;
    solid:forClass bookm:Bookmark;
    solid:instanceContainer bookmark: .

```

`my-bookmarks-registery` here is the `typeRegistrationTitle` it can be everything (uuid, ...)

**Comment by itsrezasoltani** [comment]
the app developer is responsible for providing an `indexUrl` to the method
this method will be used when there is no registry inside TypeIndex, so we have made one

**Comment by itsrezasoltani** [comment]
SolidDataSet is a JSON-LD that has typeIndex in it.
I'm not using it for now, but it is the updated typeIndex after adding the registry to it.

**Comment by michielbdejong** [comment]
OK that helps, can you add all this additional info into the docs?

**Comment by itsrezasoltani** [comment]
> OK that helps, can you add all this additional info into the docs?

Sure

**Comment by itsrezasoltani** [comment]
actually its specified in docs:
https://pondersource.github.io/solid-typeindex-support/solid-typeindex-support.typeindexhelper.registerintypeindex.html

Returns:

Promise<SolidDataset>

A Promise resolving to the updated typeIndexe dataset
